apiVersion: apps/v1
kind: Deployment
metadata:
  name: rush-capstone
  labels:
    app: rush-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rush-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rush-capstone
    spec:
      containers:
        - image: 8762783629/rush-capstone
          imagePullPolicy: Always
          name: rush-capstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rush-capstone
  labels:
    app: rush-capstone
spec:
  type: LoadBalancer
  selector:
    app: rush-capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP