apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevOps-Capstone
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: DevOps-Capstone
        role: rolling-update
    spec:
      containers:
      - name: DevOps-Capstone
        image: 8762783629/capstone
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        strategy:
          rollingUpdate:
            maxSurge: 50%
            maxUnavailable: 50%
          type: RollingUpdate