version: 2.1

jobs:
  lint-app:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
  build-docker-image:
    # docker:
    #   - image: circleci/golang:1.15
    #     auth:
    #         username: $DOCKER_USER
    #         password: $DOCKER_PASSWORD
    machine: true
    # working_directory: ~/app
    steps:
      - checkout
      # - setup_remote_docker:
      #     version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
            docker build --tag=capstone .
      - run:
          name: List Docker Image
          command: |
            docker image ls
      - run:
          name: Push Docker image into Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            TAG=capstone
            dockerpath=8762783629/$TAG
            docker tag $TAG $dockerpath
            docker push $dockerpath
            
            
workflows:
  default:
    jobs:
       - lint-app
       - build-docker-image
