version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  lint-app:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
  build-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build --tag=rush-capstone .
      - run:
          name: List Docker Image
          command: |
            docker image ls
      - run:
          name: Push Docker image into Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            TAG=rush-capstone
            dockerpath=8762783629/$TAG
            docker tag $TAG $dockerpath
            docker push $dockerpath
  
  #  used https://circleci.com/developer/orbs/orb/circleci/aws-eks#usage-create-k8s-deployment as sample
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          rush-capstone
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/rush-capstone
  
  test-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          rush-capstone
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: deployment test
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment

            
            
workflows:
  default:
    jobs:
       - lint-app
       - build-docker-image:
            requires: [lint-app]
       - aws-eks/create-cluster:
            cluster-name: rush-capstone
       - create-deployment:
            cluster-name: rush-capstone
            requires:
              - aws-eks/create-cluster
       - test-deployment:
            cluster-name: rush-capstone
            requires:
              - create-deployment
       

       